# # frontend/Dockerfile.dev
# FROM node:20-alpine

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 3000

# CMD ["npm", "start"]

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG REACT_APP_USER_AUTH_URL
ENV REACT_APP_USER_AUTH_URL=$REACT_APP_USER_AUTH_URL

ARG REACT_APP_LANGRAPH_URL
ENV REACT_APP_LANGRAPH_URL=$REACT_APP_LANGRAPH_URL


RUN npm run build

RUN npm install -g serve

ENV PORT=8080

EXPOSE 8080

CMD ["sh", "-c", "serve -s build -l $PORT"]
