<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\User.Auth.Core\User.Auth.Core.csproj" />
    <ProjectReference Include="..\User.Auth.Infrastructure\User.Auth.Infrastructure.csproj" />
  </ItemGroup>

</Project>
